### ISSUE TITLE
Images from URLs causing issues? 

### ISSUE THREAD

**Issue by doublemover** [NishantTharani/LogSeqToObsidian#9]
Error is:
```
INFO:Destination path: C:\Users\goku\Obsidian\wz_r1.md
Old note path: C:\Users\goku\logseq\journals\2022_12_01.md
Old asset path: C:\Users\goku\logseq\journals\https:\website.com\cdn\2022\20221201.jpg
New asset path: C:\Users\goku\Obsidian\journals\attachments\https:\website.com\cdn\2022\20221201.jpg
Traceback (most recent call last):
  File "C:\Users\goku\LogSeqToObsidian\convert_notes.py", line 441, in <module>
    line = update_assets(line, new_to_old_paths[fpath], fpath)
  File "C:\Users\goku\LogSeqToObsidian\convert_notes.py", line 211, in update_assets
    line = re.sub(r"!\[(.*?)]\((.*?)\)", fix_asset_embed, line)
  File "C:\Users\goku\miniconda3\lib\re.py", line 210, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "C:\Users\goku\LogSeqToObsidian\convert_notes.py", line 191, in fix_asset_embed
    shutil.copyfile(old_asset_path, new_asset_path)
  File "C:\Users\goku\miniconda3\lib\shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc:
OSError: [Errno 22] Invalid argument: 'C:\\Users\\goku\\LS\\journals\\https:\\website.com\\cdn\\2022\\20221201.jpg'
```

Line in journal is:
```
	- ![](https://website.com/cdn/2022/20221201.jpg)
```

I nosed through the script and did not see any code nearby that attempts to download these, would you like me to implement that? For now I've just removed the offending URLs from my journal. 

Thank you for writing this.

**Comment by NishantTharani** [comment]
Hi @doublemover , excellent catch! If you feel like writing some code to accomplish this, that would be much appreciated, and I'd be happy to review a PR. Otherwise, I'll leave this issue open until I get around to it :)

**Comment by lilyu1** [comment]
hello @doublemover i've fixed this here :) https://github.com/NishantTharani/LogSeqToObsidian/pull/16

**Comment by NishantTharani** [comment]
Hi @doublemover and @lilyu1 - I think I've solved this issue in a [recent commit](https://github.com/NishantTharani/LogSeqToObsidian/commit/aafe6a9ac824e137ef66e532a58e6bb203be1023) to skip any processing of http(s) assets. I think this is safer than blindly downloading http links to the user's drive. I also think it fits the tool's use case, which is to directly convert from Logseq -> Obsidian without any structural changes - if the Logseq page links to an asset on the web then the Obsidian output should too
